stages:
  prepare:
    cmd: cd notebook && papermill prep.ipynb ..\ex_notebook\prep_output2.ipynb

    deps:
      - E:/projects of camp/safety-helmet/data/data.yaml
      
    
  train:

    cmd: cd notebook && papermill train.ipynb ..\ex_notebook\train_output.ipynb

    deps:
      - E:/projects of camp/safety-helmet/data/data.yaml
      - E:/projects of camp/safety-helmet/params.yaml

    outs:
      - runs
      - yolo_optuna_mlflow
       



